# Generated by Django 4.0.1 on 2022-01-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAPPORTAL', '0002_contact_delete_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
